import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const workSans = localFont({
  src: [
    {
      path: '../../public/fonts/WorkSans-Regular.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/WorkSans-Bold.ttf',
      weight: '700'
    },
    {
      path: '../../public/fonts/WorkSans-Medium.ttf',
      weight: '500'
    }
  ],
  variable: '--font-worksans'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${workSans.variable}  font-sans antialiased grainy`}
      >
        {children}
      </body>
    </html>
  );
}
